#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

# This file is published under the terms of the same Modified BSD License that
# the unibn_setup script carries.

set -e
set -u

# Do only handle wireless connections since bonnet is a wireless.
if [[ "$1" != "wlan0" ]]
then
	exit 0
fi

# Handle the action
if [[ "$2" == up ]]
then
	# Exit if we are not connected to bonnet
	if ! iwconfig wlan0 | grep bonnet
	then
		exit 0
	fi

	/sbin/vpnc-restarter
else
	pkill vpnc-restarter
fi
