#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

if [[ "$1" != "wlan0" ]]
then
	return
fi

kill_vpnc() {
	# Kill vpnc if it is still active.
	if pgrep vpnc
	then
		vpnc-disconnect
	fi
}

# If we are not connected to "bonnet" exit and disconnect from VPN.
if ! iwconfig wlan0 | grep bonnet
then
	kill_vpnc
	return 0
fi

# Handle the action
if [[ "$2" == up ]]
then
	vpnc "$HOME/.vpnc/unibn-wlan.conf"
elif [[ "$2" == down ]]
then
	kill_vpnc
fi
