#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -u

echo '###############################################################################'
echo '#                            Uni Bonn Ubuntu Setup                            #'
echo '###############################################################################'
echo
echo 'Um die Aktionen dieses Skripts rückgängig zu machen, führen Sie folgende Befehle aus:'
echo 'sudo apt-get -y remove vpnc emacs texlive-latex base'
echo 'sudo apt-get -y autoremove'
echo 'sudo rm -f /etc/NetworkManager/dispatcher.d/99bonnet /etc/unibn-wlan.conf'
echo
echo 'Bitte geben Sie Ihre Uni Bonn Zugangsdaten ein:'
read -r -p 'Uni Bonn (HRZ) Benutzername: ' user
read -r -p 'Uni Bonn (HRZ) Passwort: ' password
echo
echo 'Dieses Skript wird gleich nach dem [sudo] Passwort fragen.'
echo 'Dies ist das Passwort für Ihren Benutzeraccount auf diesem Rechner.'
echo
echo 'I: Installiere vpn client, emacs, LaTeX.'
sudo apt-get -y install vpnc emacs texlive-latex-base

echo 'I: Erstelle Skript für automatische Einwahl ins VPN wenn im WLAN bonnet.'
sudo cat > /etc/NetworkManager/dispatcher.d/99bonnet << EOF
#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

if [[ "$1" != "wlan0" ]]
then
	return
fi

# Kill vpnc if it is still active
if pgrep vpnc
then
	vpnc-disconnect
fi

# Exit if we are not connected to bonnet
if ! iwconfig wlan0 | grep bonnet
then
	return 0
fi

# Handle the action
if [[ "$2" == up ]]
then
	vpnc /etc/unibn-wlan.conf
else
	vpnc-disconnect
fi
EOF
echo 'I: Skript erstellt.'

echo 'I: Erstelle Konfigurationsdatei für vpnc, den VPN client.'

sudo cat > /etc/unibn-wlan.conf << EOF
IPSec gateway 131.220.224.201
IPSec ID unibn-wlan
IPSec secret Ne\$e!
Xauth username $user
Xauth password $password
EOF
echo 'I: Konfigurationsdatei erstellt.

echo
echo 'Die Installation und Konfiguration ist abgeschlossen.'
