#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

# This file is published under the terms of the same Modified BSD License that
# the unibn_setup script carries.

# Since vpnc sometimes dies, this script spawns a new instance whenever it does
# that. When this script is killed by the 99bonnet script, it will disconnect
# from the VPN. As a little treat, a Gnome notification is displayed whenever
# something changes.

TEXTDOMAIN=unibn_setup

if (( UID != 0 ))
then
	echo "This script must be run as root since vpnc must be run as root."
	exit 1
fi

# Cleanup for exit, disconnect from the VPN.
destructor() {
	notify_disconnect
	vpnc-disconnect
}

trap destructor EXIT

notify_connect() {
	if which notify-send > /dev/null
	then
		notify-send -u low -t 1000 $"Connecting to VPN ..."
	fi
}

notify_disconnect() {
	if which notify-send > /dev/null
	then
		notify-send -u low -t 1000 $"Disconnecting from VPN ..."
	fi
}

# Start the VPN client in the foreground and restart it whenever it dies.
while :
do
	notify_connect
	vpnc --no-detach "$HOME/.vpnc/unibn-wlan.conf"
done

# This point in the code is virtually unreachable, the VPN will be closed out
# of with the exit hook, so there should not be anything dangling if this
# script is killed at some point.
