#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

if (( UID != 0 ))
then
	echo "This script must be run as root since vpnc must be run as root."
	exit 1
fi

# Cleanup for exit, disconnect from the VPN.
destructor() {
	vpnc-disconnect
}

trap destructor EXIT

# Start the VPN client in the foreground and restart it whenever it dies.
while :
do
	vpnc --no-detach "$HOME/.vpnc/unibn-wlan.conf"
done

# This point in the code is virtually unreachable, the VPN will be closed out
# of with the exit hook, so there should not be anything dangling if this
# script is killed at some point.
